services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=encontre.me
    volumes:
      - encontre.me_pg_data:/bitnami/postgresql

volumes:
  encontre.me_pg_data:
